purchases_app/main/urls.py
from django.urls import path
from . import views
urlpatterns = [
    path('', views.index, name='home'),
    path('', views.index, name='home'),
    path('about', views.about, name='about'),

]

purchases_app/news/urls.py
from django.urls import path
from . import views
urlpatterns = [
    path('', views.news_home, name='news_home'),
    path('create', views.create, name='create'),
    path('<int:pk>', views.NewsDetailView.as_view(), name='news-detail'),
    path('<int:pk>/update', views.NewsUpdateView.as_view(), name='news-update'),
    path('<int:pk>/delete', views.NewsDeleteView.as_view(), name='news-delete')
]

purchases_app/purchases_app/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('news/', include('news.urls')),
    path('table/', include('table.urls')),
    path('users/', include('users.urls', namespace='users')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

purchases_app/table/urls.py
from django.urls import path
from . import views
urlpatterns = [
    path('', views.table_home, name='table_home')
]

purchases_app/users/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings

from .views import login_user, logout_user

app_name = 'users'

urlpatterns = [
    path('login/', login_user, name='login'),
    path('logout/', logout_user, name='logout'),
]

purchases_app/news/models.py
from django.db import models


class Articles(models.Model):
    title = models.CharField('Название', max_length=50)
    anons = models.CharField('Анонс', max_length=250)
    full_text = models.TextField('Статья')
    date = models.DateTimeField('Дата публикации')

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return f'/news/{self.id}'

    class Meta:
        verbose_name = 'Новость'
        verbose_name_plural = 'Новости'

purchases_app/table/models.py
from django.db import models

# Create your models here.
class Purchases(models.Model):
    goods = models.CharField('Оборудование', max_length=50)
    amount = models.CharField('Количество', max_length=250)
    price = models.CharField('Цена за штуку', max_length=50)
    vendor = models.CharField('Поставщик', max_length=50)
    date = models.DateField('Дата поставки')

    def __str__(self):
        return self.goods

    class Meta:
        verbose_name = 'Закупки'
        verbose_name_plural = 'Закупки'

purchases_app/users/models.py
from django.contrib.auth.models import AbstractUser


class User(AbstractUser):
    pass

purchases_app/news/forms.py
from .models import Articles
from django.forms import ModelForm, TextInput, DateTimeInput, Textarea

class ArticlesForm(ModelForm):
    class Meta:
        model = Articles
        fields = ['title', 'anons', 'full_text', 'date']

        widgets = {
            "title": TextInput(attrs={
                'class': 'form-control',
                'placeholder': 'Название статьи'
            }),
            "anons": TextInput(attrs={
                'class': 'form-control',
                'placeholder': 'Анонс статьи'
            }),
            "date": DateTimeInput(attrs={
                'class': 'form-control',
                'placeholder': 'Дата публикации'
        }),
            "full_text": Textarea(attrs={
                'class': 'form-control',
                'placeholder': 'Текст статьи'
            })
        }

purchases_app/users/forms.py
from django import forms

class LoginUserForm(forms.Form):
    username = forms.CharField(label="Логин", widget=forms.TextInput(attrs={'class': 'form-input'}))
    password = forms.CharField(label="Пароль", widget=forms.PasswordInput(attrs={'class': 'form-input'}))

purchases_app/main/views.py
from django.shortcuts import render

def index(request):
    data = {
        'title': 'Главная страница',
        'values': ['Контроль оплат', 'Пароли личных кабинетов'],
        'obj': {
            'goods': 'Товарный калькулятор',
            'tax': 'Калькулятор НДС',
        }
    }
    return render(request, 'main/index.html', data)

def about(request):
    return render(request, 'main/about.html')

purchases_app/news/views.py
from django.shortcuts import render, redirect
from .models import Articles
from .forms import ArticlesForm
from django.views.generic import DetailView, UpdateView, DeleteView


# Create your views here.

def news_home(request):
    news = Articles.objects.order_by('-date')
    return render(request, 'news/news_home.html', {'news': news})

class NewsDetailView(DetailView):
    model = Articles
    template_name = 'news/detail_view.html'
    context_object_name = 'article'

class NewsUpdateView(UpdateView):
    model = Articles
    template_name = 'news/create.html'
    form_class = ArticlesForm

class NewsDeleteView(DeleteView):
    model = Articles
    success_url = '/news'
    template_name = 'news/news-delete.html'

def create(request):
    error = ''
    if request.method == 'POST':
        form = ArticlesForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('home')
        else:
            error = 'Wrong form'
    form = ArticlesForm()

    data = {
        'form': form,
        'error': error
    }

    return render(request, 'news/create.html', data)

purchases_app/table/views.py
from django.shortcuts import render
from .models import Purchases

# Create your views here.
def table_home(request):
    goods = Purchases.objects.all()
    return render(request, 'table/table_home.html', goods)

purchases_app/users/views.py
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse

from .forms import LoginUserForm


# Create your views here.
def login_user(request):
    if request.method == 'POST':
        form = LoginUserForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            user = authenticate(request, username=cd['username'], password=cd['password'])
            if user and user.is_active:
                login(request, user)
                return HttpResponseRedirect(reverse('home'))
    else:
        form = LoginUserForm()

    return render(request, 'users/login.html', {'form': form})


def logout_user(request):
    logout(request)
    return HttpResponseRedirect(reverse('users:login'))

purchases_app/main/templates/main/about.html
{% extends 'main/layout.html' %}

{% block title %}О программе{% endblock %}

{% block content %}
    <div class="features">
    <h1>О программе</h1>
    <p>Данная программа была создана для контроля за закупками товара. Надеюсь, вам будет удобно ей пользоваться</p>
    <a href="{% url 'home' %}" class="btn btn-danger">Начать пользоваться</a>
    </div>
{% endblock %}

purchases_app/main/templates/main/index.html
{% extends 'main/layout.html' %}

{% block title %}{{ title }}{% endblock %}

{% block content %}
    <div class="features">
        <h1>{{ title }}</h1>
        <p>Выберите интересующий раздел</p>
        <a href="{% url 'about' %}" class="btn btn-warning">О программе</a><br>
        <a href="{% url 'table_home' %}" class="btn btn-warning">Таблица учета заказов</a>

        {% for val in values %}
            <p>{{ val|upper }}</p>
        {% endfor %}

        {% for el in obj.values %}
            <p>{{ el }}</p>
        {% endfor %}

    </div>
{% endblock %}

purchases_app/main/templates/main/layout.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{% block title %}{% endblock %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'main/css/main.css' %}">
    <script src="https://kit.fontawesome.com/9ac1cea447.js" crossorigin="anonymous"></script>
</head>
<body>
<header class="#" style="background-color: #181818;">
    <nav>
        <ul class="nav justify-content-end">
            {% if user.is_authenticated %}
                <li class="d-flex align-items-center"><span>{{ user.username }} </span> | <a class="nav-link active" aria-current="page" href="{% url 'users:logout' %}" >Выйти</a></li>
            {% else %}
                <li class="d-flex align-items-center"><a href="{% url 'users:login' %}" class="nav-link active" aria-current="page">Личный кабинет</a> | <a href="#" class="nav-link active" aria-current="page">Регистрация</a></li>
            {% endif %}
        </ul>
    </nav>
</header>
    <aside>
        <img src="{% static 'main/img/picture.png' %}" alt="Лого" width="100" height="100">
        <span class="logo">Закупки</span>
        <h3>Навигация</h3>

        <ul>

            <li><a href="{% url 'home' %}"><i class="fa-solid fa-house" style="color: #ffff;"></i>Главная</a></li>
            <li><a href="{% url 'about' %}"><i class="fa-regular fa-address-card" style="color: #ffff;"></i>О программе</a></li>
            <li><a href="{% url 'news_home' %}"><i class="fa-solid fa-rectangle-ad" style="color: #ffff;"></i>Новости</a></li>
            <li><a href=""><i class="fa-solid fa-envelope" style="color: #ffff;"></i>Контакты</a></li>
            <li><a href="{% url 'create' %}"><button class="btn btn-info"><i class="fas fa-plus-circle" style="color: #ffff;"></i>Добавить новость</button></a></li>

        </ul>
    </aside>
    <main>
        {% block content %}
        {% endblock %}
    </main>

</body>
</html>

purchases_app/news/templates/news/create.html
{% extends 'main/layout.html' %}

{% block title %}Форма по добавлению статьи{% endblock %}

{% block content %}
    <div class="features">
        <h1>Форма по добавлению статьи</h1>
        <form method="post">
            {% csrf_token %}
            {{ form.title }}<br>
            {{ form.anons }}<br>
            {{ form.full_text }}<br>
            {{ form.date }}<br>
            <span>{{ error }}</span>
            <button class="btn btn-success" type="submit">Сохранить</button>
        </form>
    </div>
{% endblock %}

purchases_app/news/templates/news/detail_view.html
{% extends 'main/layout.html' %}

{% block title %}{{ article.title }}{% endblock %}

{% block content %}
    <div class="features">
        <h1>{{ article.title }}</h1>
        <p>{{ article.date }}</p>
        <p>{{ article.full_text }}</p>
        <a href="{% url 'news-delete' article.id %}" class="btn btn-danger">Удалить</a>
        <a href="{% url 'news-update' article.id %}" class="btn btn-info">Редактировать</a>

    </div>
{% endblock %}

purchases_app/news/templates/news/news-delete.html
{% extends 'main/layout.html' %}

{% block title %}Удаление статьи{% endblock %}

{% block content %}
    <div class="features">
        <h1>Удаление статьи</h1>
        <form method="post">
            {% csrf_token %}
            {{ form.title }}<br>
            {{ form.anons }}<br>
            {{ form.full_text }}<br>
            {{ form.date }}<br>
            <button class="btn btn-success" type="submit">Удалить статью</button>
        </form>
    </div>
{% endblock %}

purchases_app/news/templates/news/news_home.html
{% extends 'main/layout.html' %}

{% block title %}Новости на сайте{% endblock %}

{% block content %}
    <div class="features">
        <h1>Новости на сайте</h1>
        {% if news %}
            {% for el in news %}
                <div class="alert alert-warning">
                    <h3>{{ el.title }}</h3>
                    <p>{{ el.anons }}</p>
                    <a href="{% url 'news-detail' el.id %}" class="btn btn-warning">Прочитать статью</a>
                </div>
            {% endfor %}
        {% else  %}
            <p>У вас нет записей</p>
        {% endif %}

        {# Комментарий #}
    </div>
{% endblock %}

purchases_app/table/templates/table/table_home.html
<div class="row g-10">
  <div class="col-sm-10">
    <input type="text" class="form-control" placeholder="Оборудование" aria-label="Goods">
  </div>
  <div class="col-sm">
    <input type="text" class="form-control" placeholder="Количество" aria-label="Amount">
  </div>
  <div class="col-sm">
    <input type="text" class="form-control" placeholder="Цена за шт" aria-label="Price">
  </div>
  <div class="col-sm">
    <input type="text" class="form-control" placeholder="Поставщик" aria-label="Vendor">
  </div>
  <div class="col-sm">
    <input type="date" class="form-control" placeholder="Дата поставки" aria-label="Date">
  </div>
</div>

purchases_app/users/templates/users/login.html
{% extends 'main/layout.html' %}

{% block title %}Авторизация{% endblock %}

{% block content %}
    <div class="features">
        <h1>Вход в личный кабинет</h1>
        <form method="post">
            {% csrf_token %}
            {{ form.username }}<br>
            {{ form.password }}<br>
            <span>{{ error }}</span>
            <button class="btn btn-success save-button" type="submit">Войти в личный кабинет</button>
        </form>
    </div>
{% endblock %}